"""Add scheduling, analytics, and tags features

Revision ID: 221af62b53e2
Revises: 
Create Date: 2025-10-18 17:03:05.289671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221af62b53e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscriber_tag_associations',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['subscriber_tags.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'tag_id')
    )
    op.create_table('email_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_log_id', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['email_log_id'], ['email_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_opens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_log_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['email_log_id'], ['email_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_scheduled', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaign_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_status'), ['status'], unique=False)

    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriber_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriber_name'))
        batch_op.drop_index(batch_op.f('ix_subscriber_is_active'))
        batch_op.drop_index(batch_op.f('ix_subscriber_created_at'))
        batch_op.drop_column('unsubscribed_at')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_created_at'))
        batch_op.drop_column('is_scheduled')
        batch_op.drop_column('scheduled_at')

    op.drop_table('email_opens')
    op.drop_table('email_clicks')
    op.drop_table('subscriber_tag_associations')
    op.drop_table('subscriber_tags')
    # ### end Alembic commands ###
