"""Add is_archived and archived_at to Campaign model

Revision ID: 815fe2375955
Revises: 221af62b53e2
Create Date: 2025-10-18 17:14:54.388492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815fe2375955'
down_revision = '221af62b53e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaign_is_archived'), ['is_archived'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_is_archived'))
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
